# Production overrides for docker-compose
version: '3.8'

services:
  document-upload-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:8443;http://+:8080
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - /var/lib/document-upload-api/uploads:/app/uploads
      - /var/log/document-upload-api:/app/logs
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
